export class ApiError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly status = 400,
    public readonly rule?: string,
  ) {
    super(message);
  }
}

export const Codes = {
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  SELF_TRANSFER: "SELF_TRANSFER",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
  INVALID_RECIPIENT: "INVALID_RECIPIENT",
  INVALID_QR: "INVALID_QR",
  LINK_NOT_FOUND: "LINK_NOT_FOUND",
  LINK_REVOKED: "LINK_REVOKED",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  TRANSFER_NOT_ALLOWED: "TRANSFER_NOT_ALLOWED",
  WALLET_SUSPENDED: "WALLET_SUSPENDED",
  DAILY_LIMIT_EXCEEDED: "DAILY_LIMIT_EXCEEDED",
  RISK_BLOCKED: "RISK_BLOCKED",
  ABUSE_BLOCKED: "ABUSE_BLOCKED",
  ABUSE_REVIEW: "ABUSE_REVIEW",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  REQUEST_NOT_PAYABLE: "REQUEST_NOT_PAYABLE",
  REQUEST_ALREADY_PROCESSED: "REQUEST_ALREADY_PROCESSED",
  SHARES_SUM_MISMATCH: "SHARES_SUM_MISMATCH",
  SPLIT_NOT_FOUND: "SPLIT_NOT_FOUND",
  SHARE_NOT_PAYABLE: "SHARE_NOT_PAYABLE",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  PHONE_NOT_VERIFIED: "PHONE_NOT_VERIFIED",
  INVALID_OTP: "INVALID_OTP",
  OTP_EXPIRED: "OTP_EXPIRED",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  ALREADY_TRUSTED: "ALREADY_TRUSTED",
  CANNOT_TRUST_SELF: "CANNOT_TRUST_SELF",
  RATE_LIMITED: "RATE_LIMITED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;
